### ISSUE TITLE
DONT Give EthanEdits credit 😂

### ISSUE THREAD

**Issue by Anonymoushacker4926** [Snaacky/Diamond#15]
Expose this copy and paster looking headass boi 😂 stealing your code!!!

Video - https://youtu.be/CnCPs0XUbj8
Channel - https://youtube.com/c/EthanEDITS1

**Comment by Snaacky** [comment]
@Anonymoushacker4926 Is this a joke? I have no idea who that person is but read their video description. I only skimmed the video but it seems like it's just 12 minutes of him typing out my script while reading it from a second monitor.

**Comment by Anonymoushacker4926** [comment]
Wait a fucking second... he must've bamboozled both of us. I guess he stole from you or you still stole but wtf 😂
