### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'base_address'

### ISSUE THREAD

**Issue by kir486680** [Snaacky/Diamond#3]
client = pymem.process.module_from_name(pm.process_id, "client_panorama.dll").base_address
AttributeError: 'NoneType' object has no attribute 'base_address'

**Comment by saulgodman84** [comment]
Yes i have the same error.

**Comment by Snaacky** [comment]
Sorry for the last response.

This was fixed in the most recent commit.
